package(default_visibility = ["//tfx_bsl:__subpackages__"])

licenses(["notice"])  # Apache 2.0

# Developers: use these two macros to define c++ or python proto targets.
# load("//tfx_bsl:build_macros.bzl", "tfx_bsl_proto_library", "tfx_bsl_py_proto_library")

filegroup(
    name = "public_protos",
    srcs = [],
)
